name: Pull module/submodule
run-name: ${{ github.actor }} is pulling module

on:
  workflow_dispatch:
    inputs:
      repo_name: 
        description: 'Module/Submodule name to pull'
        default: 'imputation'
        required: true
        type: string

      repo_type:
        description: 'Type of repo'
        default: 'module'
        required: true
        type: choice
        options:
        - module
        - subworkflow
  
  workflow_call:
    inputs:
      repo_name: 
        description: 'Module/Submodule name to pull'
        required: true
        type: string

      repo_type:
        description: 'Type of repo'
        required: true
        type: string

jobs:
  pulling_module:
    runs-on: ubuntu-20.04
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Add SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Prepare global variables
        run: |
          echo "REPO_LINK=git@github.com:KTest-VN/${{inputs.repo_name }}.git" >> $GITHUB_ENV
          echo "REPO_NAME=${{inputs.repo_name }}" >> $GITHUB_ENV
          echo "REPO_TYPE=${{inputs.repo_type }}" >> $GITHUB_ENV

      - name: Check whether the ${{ env.REPO_TYPE }} is created.
        run: |
          if [ -d "./${{ env.REPO_TYPE }}s/ktest/${{ env.REPO_NAME }}" ]; then
            echo "REPO_EXIST=1" >> $GITHUB_ENV
          else
            echo "REPO_EXIST=0" >> $GITHUB_ENV
          fi   
      
      - name: Checking ${{ env.REPO_TYPE }} if exist
        if: ${{ env.REPO_EXIST }}
        run: |
          REMAIN_COMMIT=`git log -n 1 --pretty=format:"%s" ./${{ env.REPO_TYPE }}s/ktest/${{ env.REPO_NAME }}/main.nf | sed 's|@(.*)$|\1|g'`
          rm -rf ./${{ env.REPO_TYPE }}s/ktest/${{ env.REPO_NAME }}

      - name: Clone the ${{ env.REPO_TYPE }}
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git fetch
          git clone ${{ env.REPO_LINK }} ./${{ env.REPO_TYPE }}s/ktest/${{ env.REPO_NAME }}
      
      - name: Get last commit of ${{ env.REPO_TYPE }}
        run: |
          cd ./${{ env.REPO_TYPE }}s/ktest/${{ env.REPO_NAME }}
          LATEST_COMMIT=`git log -n 1 origin/main --pretty=format:"%h"`
          echo "LATEST_COMMIT=$LATEST_COMMIT" >> $GITHUB_ENV

      - name: Clean git of ${{ env.REPO_TYPE }}
        run: |
          rm -rf ./${{ env.REPO_TYPE }}s/ktest/${{ env.REPO_NAME }}/.git/

      - name: Commit changes
        run: |
          git reset
          git add ./${{ env.REPO_TYPE }}s/ktest/${{ env.REPO_NAME }}
          git commit -m "${{ github.actor }} add ${{ env.REPO_TYPE }} ${{ env.REPO_NAME }} from KTest-VN/${{ env.REPO_NAME }}@${{ env.LATEST_COMMIT }}"
      
      - name: Push changes
        run: git push origin main
          
