name: Update all modules
run-name: Update module

on:
  schedule:
    - cron: '0 0 28-31 * *'
  workflow_dispatch:


jobs:
  list_module:

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Add SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
      
      - name: Get list all module
        run: |
          json_list=$(echo `ls ./modules/ktest` | tr -d '\n' | jq -R -s -c 'split(" ")')
          echo "MODULE_LIST=$json_list" >> $GITHUB_ENV

  update_module:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        module_name: ${{ fromJson(env.MODULE_LIST) }}
    steps:
      - name: Update modules
        uses: ./.github/workflows/pull-module.yml
        with:
          module_name: ${{ matrix.module_name }}
          repo_type: module
      